"""Initial migration

Revision ID: 1d91c5edef60
Revises: 6c5f7ebdf368
Create Date: 2025-01-31 02:44:35.115036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d91c5edef60'
down_revision = '6c5f7ebdf368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_rented', sa.Boolean(), nullable=True))
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('is_rented')

    # ### end Alembic commands ###
