"""Fixed Book model

Revision ID: 55444e0b1341
Revises: 1d91c5edef60
Create Date: 2025-01-31 02:51:49.652977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55444e0b1341'
down_revision = '1d91c5edef60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=128), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('is_rented')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_rented', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('author')

    # ### end Alembic commands ###
