"""Fixed model issues

Revision ID: 6c5f7ebdf368
Revises: 1737da8eacfe
Create Date: 2025-01-31 02:06:48.683408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5f7ebdf368'
down_revision = '1737da8eacfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('author', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('genre', sa.String(length=128), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('Genre')
        batch_op.drop_column('Title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Title', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('Genre', sa.VARCHAR(length=128), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('genre')
        batch_op.drop_column('author')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
