"""Added is_rented column to Book

Revision ID: ec9574d1d488
Revises: 55444e0b1341
Create Date: 2025-01-31 04:23:09.220963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9574d1d488'
down_revision = '55444e0b1341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_rented', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('is_rented')

    # ### end Alembic commands ###
